export const tableData = [
    {
        "TableName": "Transaction",
        "ColumnOrder": "id, SourceDate, Status, IsReady, Notes, CategoryName, PostedDate, AsOfDate, SetleDate, ContractualSettleDate, ContractualSettlementDate, BaseCurrencyCode, LocalCurrencyCode, SourceAccount, MellonSecurityID, SecurityType, MainTransactionNumber, SubTransactionNumber, LinedTransactionNumber, IASReferenceNumber, TransactionNumber, MainTransactionCode, TransactionCode, TaxCode, EffectiveDate, TradeDate, Shares, Shares2, SharesPar, SourceName, CreatedUser, CreatedDateTime, UpdatedUser, UpdatedDateTime",
        "AllowSelect": true,
        "AllowInsert": true,
        "AllowUpdate": true,
        "AllowDelete": true,
        "ID": 7,
        "ContextView": null,
        "ContextParameters": null,
        "SchemaName": "CIBC",
        "AdGroup": "Dynamics 365 DEV",
        "PrimaryKey": "Id",
        "Server": null,
        "Database": "NWMME"
    },
    {
        "TableName": "TransactionExclusion",
        "ColumnOrder": "Id, SourceDate, CategoryName, PostedDate, AsOfDate, SettleDate, ContractualSettleDate, ContractualSettlementDate, AcctBaseCurrencyCode, BaseCurrency, BaseCurrencyCode, LocalCurrencyCode, PayableCurrencyCode, ReceivableCurrencyCode, SourceAccount, SourceAccountNumber, MellonSecurityID, SecurityType, MainTransactionNumber, SubTransactionNumber, LinkedTransactionNumber, IASReferenceNumber, TransactionNumber, MainTransactionCode, TransactionCode, TaxCode, EffectiveDate, TradeDate, Shares, Shares2, SharesPar, LocalAmount, LocalCommission, LocalCommissionAndFees, LocalFees, LocalInterestBoughtSold, LocalPrice, LocalSettledAmount, PayableUnits, ReceivableUnits, Description, Description1, Description2, Description3, Description4, TaxCodeDescription, TransactionDescription, AccountStatus, BaseAmount, BaseCommission, BaseCommissionAndFees, BaseCurrencyName, BaseFees, BaseIncomeAmount, BaseInterestBoughtSold, BasePrice, BaseSettledAmount, CancellationDate, ExchangeRate, IASRecordLocator, LocalCurrencyName, LocalIncomeAmount, PayableCurrencyName, PayableSettleDate, ReceivableCurrencyName, ReceivableSettleDate, ReportingAccountName, ReportingAccountNumber, SecurityDescription1, SecurityDescription2, SettleAmount, SettleCommission, SettleFees, SettleInterestBoughtSold, SettlePrice, SourceAccountName, SubTransactionCode, TradeExDate, TradeType, TransactionCategoryCode, TransactionCategoryDescription, TransactionStatus, TransNumberRef, SourceName, AssociatedTransactionKey, IsEnabled, Notes, CreatedUser, CreatedDateTime, UpdatedUser, UpdatedDateTime",
        "AllowSelect": true,
        "AllowInsert": true,
        "AllowUpdate": true,
        "AllowDelete": true,
        "ID": 23,
        "ContextView": null,
        "ContextParameters": null,
        "SchemaName": "CIBC",
        "AdGroup": "Dynamics 365 DEV",
        "PrimaryKey": "Id",
        "Server": null,
        "Database": "nwmme"
    },
    {
        "TableName": "ColumnAllowableValues",
        "ColumnOrder": "id, ColumnId, AllowedValue, CreatedUser, CreatedDateTime, UpdatedUser, UpdatedDateTime",
        "AllowSelect": true,
        "AllowInsert": true,
        "AllowUpdate": true,
        "AllowDelete": true,
        "ID": 1,
        "ContextView": null,
        "ContextParameters": null,
        "SchemaName": "Config",
        "AdGroup": "Dynamics 365 DEV",
        "PrimaryKey": "Id",
        "Server": null,
        "Database": "NWMME"
    },
    {
        "TableName": "ColumnConfig",
        "ColumnOrder": "id, TableId, ColumnName, ColumnDescription, MinValue, MaxValue, AllowEdit, IsVisible, Enabled, CreatedUser, CreatedDateTime, UpdatedUser, UpdatedDateTime",
        "AllowSelect": true,
        "AllowInsert": true,
        "AllowUpdate": true,
        "AllowDelete": true,
        "ID": 2,
        "ContextView": null,
        "ContextParameters": null,
        "SchemaName": "Config",
        "AdGroup": "Dynamics 365 DEV",
        "PrimaryKey": "Id",
        "Server": null,
        "Database": "NWMME"
    },
    {
        "TableName": "NotificationList",
        "ColumnOrder": "id, TableId, NotifyEmail, Enabled, CreatedUser, CreatedDateTime, UpdatedUser, UpdatedDateTime",
        "AllowSelect": true,
        "AllowInsert": true,
        "AllowUpdate": true,
        "AllowDelete": true,
        "ID": 3,
        "ContextView": null,
        "ContextParameters": null,
        "SchemaName": "Config",
        "AdGroup": "Dynamics 365 DEV",
        "PrimaryKey": "Id",
        "Server": null,
        "Database": "NWMME"
    },
    {
        "TableName": "TableAuthorization",
        "ColumnOrder": "id, TableId, AdGroup, AllowSelect, AllowInsert, AllowUpdate, AllowDelete, Enabled, CreatedUser, CreatedDateTime, UpdatedUser, UpdatedDateTime",
        "AllowSelect": true,
        "AllowInsert": true,
        "AllowUpdate": true,
        "AllowDelete": true,
        "ID": 4,
        "ContextView": null,
        "ContextParameters": null,
        "SchemaName": "Config",
        "AdGroup": "Dynamics 365 DEV",
        "PrimaryKey": "Id",
        "Server": null,
        "Database": "NWMME"
    },
    {
        "TableName": "TableConfig",
        "ColumnOrder": "id, Server, Database, TableName, TableDescription, SchemaName, ColumnOrder, ContextView, ContextParameters, Enabled, CreatedUser, CreatedDateTime, UpdatedUser, UpdatedDateTime",
        "AllowSelect": true,
        "AllowInsert": true,
        "AllowUpdate": true,
        "AllowDelete": true,
        "ID": 5,
        "ContextView": null,
        "ContextParameters": null,
        "SchemaName": "Config",
        "AdGroup": "Dynamics 365 DEV",
        "PrimaryKey": "Id",
        "Server": null,
        "Database": "NWMME"
    },
    {
        "TableName": "Transaction",
        "ColumnOrder": "[Id],[SourceName],[SourceDate],[SEQNO],[SourceAccountId],[SourceProductId],[SourceOriginatingProductId],[AccountNumber],[TransactionCode],[SecurityClass],[SecurityDescription],[Description],[CUSIP],[TradeDate],[SettleDate],[ProcessDate],[Quantity],[Amount],[FundType],[Cost],[ExchangeRate],[RR],[UnitPrice],[Commission],[Tax],[AccruedInt],[Fees],[Status],[IsReady],[Notes],[AssociatedTransactionKey],[CreatedUser],[CreatedDateTime],[UpdatedUser],[UpdatedDateTime]",
        "AllowSelect": true,
        "AllowInsert": true,
        "AllowUpdate": true,
        "AllowDelete": true,
        "ID": 29,
        "ContextView": null,
        "ContextParameters": null,
        "SchemaName": "Credential",
        "AdGroup": "Dynamics 365 DEV",
        "PrimaryKey": "Id",
        "Server": null,
        "Database": "NWMME"
    },
    {
        "TableName": "Account",
        "ColumnOrder": "id, SourceDate, Status, IsReady, Notes, SourceName, AccountNumber, ClassificationCode, AccountOpenDate, Currency, HoldingID, CreatedUser, CreatedDateTime, UpdatedUser, UpdatedDateTime",
        "AllowSelect": true,
        "AllowInsert": true,
        "AllowUpdate": true,
        "AllowDelete": true,
        "ID": 6,
        "ContextView": "uspGMEContextViewAccount",
        "ContextParameters": "AccountNumber",
        "SchemaName": "dbo",
        "AdGroup": "Dynamics 365 DEV",
        "PrimaryKey": "Id",
        "Server": null,
        "Database": "NWMME"
    },
    {
        "TableName": "AccountExclusion",
        "ColumnOrder": "Id, SourceName, AccountNKey, Note, IsEnabled, CreatedUser, CreatedDateTime, UpdatedUser, UpdatedDateTime",
        "AllowSelect": true,
        "AllowInsert": true,
        "AllowUpdate": true,
        "AllowDelete": true,
        "ID": 19,
        "ContextView": null,
        "ContextParameters": null,
        "SchemaName": "dbo",
        "AdGroup": "Dynamics 365 DEV",
        "PrimaryKey": "Id",
        "Server": null,
        "Database": "nwmme"
    },
    {
        "TableName": "Price",
        "ColumnOrder": "id, SourceDate, Status, IsReady, Notes, SourceName, ProductId, PriceDate, Currency, ClosePrice, BidPrice, AskPrice, PriceSource, CreatedUser, CreatedDateTime, UpdatedUser, UpdatedDateTime",
        "AllowSelect": true,
        "AllowInsert": true,
        "AllowUpdate": true,
        "AllowDelete": true,
        "ID": 9,
        "ContextView": "uspGMEContextViewPrice",
        "ContextParameters": "SourceName, ProductId",
        "SchemaName": "dbo",
        "AdGroup": "Dynamics 365 DEV",
        "PrimaryKey": "Id",
        "Server": null,
        "Database": "NWMME"
    },
    {
        "TableName": "Product",
        "ColumnOrder": "id, SourceDate, Status, IsReady, Notes, SourceProductId, SourceName, ProductShortName, ProductFullName, CusipNumber, ISIN, Symbol, InterestRate, MaturityDate, CompoundMethod, CompoundsPerYear, CarrierCode, DividendFrequency, IsCloseEnded, IsPreferred, IsConvertible, Currency, CallDate, CallAmount, PutDate, PutAmount, ProductCategory, CreatedUser, CreatedDateTime, UpdatedUser, UpdatedDateTime",
        "AllowSelect": true,
        "AllowInsert": true,
        "AllowUpdate": true,
        "AllowDelete": true,
        "ID": 11,
        "ContextView": null,
        "ContextParameters": null,
        "SchemaName": "dbo",
        "AdGroup": "Dynamics 365 DEV",
        "PrimaryKey": "Id",
        "Server": null,
        "Database": "NWMME"
    },
    {
        "TableName": "ProductDeduplication",
        "ColumnOrder": "id, SourceDate, Status, IsReady, Notes, SourceName, SourceNKey, ReplaceSourceName, ReplaceNKey, CreatedUser, CreatedDateTime, UpdatedUser, UpdatedDateTime",
        "AllowSelect": true,
        "AllowInsert": true,
        "AllowUpdate": true,
        "AllowDelete": true,
        "ID": 10,
        "ContextView": "uspGMEContextViewProductDeduplication",
        "ContextParameters": "SourceName, SourceNKey, ReplaceSourceName, ReplaceNKey",
        "SchemaName": "dbo",
        "AdGroup": "Dynamics 365 DEV",
        "PrimaryKey": "Id",
        "Server": null,
        "Database": "NWMME"
    },
    {
        "TableName": "ProductExclusion",
        "ColumnOrder": "Id, SourceName, ProductNKey, Note, IsEnabled, CreatedUser, CreatedDateTime, UpdatedUser, UpdatedDateTime",
        "AllowSelect": true,
        "AllowInsert": true,
        "AllowUpdate": true,
        "AllowDelete": true,
        "ID": 20,
        "ContextView": null,
        "ContextParameters": null,
        "SchemaName": "dbo",
        "AdGroup": "Dynamics 365 DEV",
        "PrimaryKey": "Id",
        "Server": null,
        "Database": "nwmme"
    },
    {
        "TableName": "ProductUnitOfMeasure",
        "ColumnOrder": "id, SourceDate, Status, IsReady, Notes, SourceName, SecurityCode, SecurityName, SecurityGroup, UnitOfMeasure, IsMultiplyUOM, RemainingPrincipalFactor, DatedInterestRate, EffectiveDate, EndDate, CreatedUser, CreatedDateTime, UpdatedUser, UpdatedDateTime",
        "AllowSelect": true,
        "AllowInsert": true,
        "AllowUpdate": true,
        "AllowDelete": true,
        "ID": 12,
        "ContextView": null,
        "ContextParameters": null,
        "SchemaName": "dbo",
        "AdGroup": "Dynamics 365 DEV",
        "PrimaryKey": "Id",
        "Server": null,
        "Database": "NWMME"
    },
    {
        "TableName": "RecurringPrice",
        "ColumnOrder": "id, SourceDate, Status, IsReady, Notes, SourceName, ProductId, PriceDate, Currency, ClosePrice, BidPrice, AskPrice, PriceSource, AbbrName, Type, CreatedUser, CreatedDateTime, UpdatedUser, UpdatedDateTime",
        "AllowSelect": true,
        "AllowInsert": true,
        "AllowUpdate": true,
        "AllowDelete": true,
        "ID": 13,
        "ContextView": "uspGMEContextViewRecurringPrice",
        "ContextParameters": "SourceName, ProductId",
        "SchemaName": "dbo",
        "AdGroup": "Dynamics 365 DEV",
        "PrimaryKey": "Id",
        "Server": null,
        "Database": "NWMME"
    },
    {
        "TableName": "TransactionExclusion",
        "ColumnOrder": "Id, TransactionId, SourceTransactionId, Note, IsEnabled, CreatedUser, CreatedDateTime, UpdatedUser, UpdatedDateTime",
        "AllowSelect": true,
        "AllowInsert": true,
        "AllowUpdate": true,
        "AllowDelete": true,
        "ID": 21,
        "ContextView": null,
        "ContextParameters": null,
        "SchemaName": "dbo",
        "AdGroup": "Dynamics 365 DEV",
        "PrimaryKey": "Id",
        "Server": null,
        "Database": "nwmme"
    },
    {
        "TableName": "Transaction",
        "ColumnOrder": "Id, SourceDate, IsReady, Status, Account_Number, Security_Number, Value_Date, Trade_Date, Entry_Type, Description, Quantity, Net_Amount, Price, JNFGTransId, Notes",
        "AllowSelect": true,
        "AllowInsert": true,
        "AllowUpdate": true,
        "AllowDelete": true,
        "ID": 18,
        "ContextView": null,
        "ContextParameters": null,
        "SchemaName": "NBCN",
        "AdGroup": "Dynamics 365 DEV",
        "PrimaryKey": "Id",
        "Server": null,
        "Database": "NWMME"
    },
    {
        "TableName": "TransactionExclusion",
        "ColumnOrder": "Id, SourceDate, Account_Number, Security_Number, Value_Date, Process_Date, Trade_Date, Quantity_Is_Valid, Amount_Is_Valid, Item_Is_Trade, Item_Is_Exchange, Item_Is_Reversal, Entry_Type, Description, Quantity, Net_Amount, Price, Price_Funds, Fee, Drip_Amount, SourceOriginating_SecurityNumber, SourceName, AssociatedTransactionKey, IsEnabled, Notes, CreatedUser, CreatedDateTime, UpdatedUser, UpdatedDateTime",
        "AllowSelect": true,
        "AllowInsert": true,
        "AllowUpdate": true,
        "AllowDelete": true,
        "ID": 24,
        "ContextView": null,
        "ContextParameters": null,
        "SchemaName": "NBCN",
        "AdGroup": "Dynamics 365 DEV",
        "PrimaryKey": "Id",
        "Server": null,
        "Database": "nwmme"
    },
    {
        "TableName": "Transaction",
        "ColumnOrder": "id, SourceDate, Status, IsReady, Notes, Price, Quantity, Amount, account_cd, branch_cd, cmmsn_amt, currency_cd, debit_credit_cd, desc_trans_sec_txt, entry_cd, net_trans_amt, prc_sec_amt, share_trans_qty, tax_wthld_amt, trade_dt, tran_total_amt, trans_total_amt, trans_value_dt, transaction_dt, type_account_cd, SourceOriginating_security_adp_nbr, SourceName, CategoryName, AssociatedTransactionKey, CreatedUser, CreatedDateTime, UpdatedUser, UpdatedDateTime",
        "AllowSelect": true,
        "AllowInsert": true,
        "AllowUpdate": true,
        "AllowDelete": true,
        "ID": 8,
        "ContextView": "uspGMEContextViewPensonTransaction",
        "ContextParameters": "Branch_Cd, Account_Cd, Currency_Cd, Type_Account_Cd",
        "SchemaName": "PENSON",
        "AdGroup": "Dynamics 365 DEV",
        "PrimaryKey": "Id",
        "Server": null,
        "Database": "NWMME"
    },
    {
        "TableName": "Transaction",
        "ColumnOrder": "id, SourceDate, Status, IsReady, Notes, Account_Number, Security_Number, Value_Date, Process_Date, Trade_Date, Quantity_Is_Valid, Amount_Is_Valid, Item_Is_Trade, Item_Is_Exchange, Item_Is_Reversal, Entry_Type, Description, Quantity, Net_Amount, Price, Price_Funds, Fee, Drip_Amount, SourceOriginating_SecurityNumber, SourceName, AssociatedTransactionKey, JNFGTransId, IsCancelReversal, CreatedUser, CreatedDateTime, UpdatedUser, UpdatedDateTime",
        "AllowSelect": true,
        "AllowInsert": true,
        "AllowUpdate": true,
        "AllowDelete": true,
        "ID": 16,
        "ContextView": "uspGMEContextViewTdTransaction",
        "ContextParameters": "Account_Number",
        "SchemaName": "TD",
        "AdGroup": "Dynamics 365 DEV",
        "PrimaryKey": "Id",
        "Server": null,
        "Database": "NWMME"
    },
    {
        "TableName": "TransactionExclusion",
        "ColumnOrder": "Id, SourceDate, Account_Number, Security_Number, Value_Date, Process_Date, Trade_Date, Quantity_Is_Valid, Amount_Is_Valid, Item_Is_Trade, Item_Is_Exchange, Item_Is_Reversal, Entry_Type, Description, Quantity, Net_Amount, Price, Price_Funds, Fee, Drip_Amount, SourceOriginating_SecurityNumber, SourceName, AssociatedTransactionKey, IsEnabled, Notes, CreatedUser, CreatedDateTime, UpdatedUser, UpdatedDateTime",
        "AllowSelect": true,
        "AllowInsert": true,
        "AllowUpdate": true,
        "AllowDelete": true,
        "ID": 22,
        "ContextView": null,
        "ContextParameters": null,
        "SchemaName": "TD",
        "AdGroup": "Dynamics 365 DEV",
        "PrimaryKey": "Id",
        "Server": null,
        "Database": "nwmme"
    }
]